# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 0.1.5

# Set the OS, Python version, and other tools you might need
build:
  os: alpine
  tools:
    python: "3.x"

