name: Improvement
description: Suggest an improvement to an existing PurpleCli feature
title: "[Improvement]: "

body:
  - type: dropdown
    attributes:
      label: Version Channel
      description: Which PurpleCli version channel are you using?
      options:
        - Stable
        - Unstable
    validations:
      required: true

  - type: input
    attributes:
      label: PurpleCli Version
      description: Enter the version you are using.
      placeholder: "0.1.5"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: Describe how the feature currently works.
      placeholder: |
        Currently, PurpleCli...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Improvement
      description: Describe how you think it could be improved.
      placeholder: |
        It would be better if PurpleCli...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why Should This Be Improved?
      description: Explain why this change would be useful.
      placeholder: |
        This would improve PurpleCli because...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: Add anything else that may help.
      placeholder: Additional information or examples.
    validations:
      required: false
